apiVersion: v1
kind: Service
metadata:
  name: gptoss-service
spec:
  type: NodePort
  selector:
    job-name: gptoss-server    # IMPORTANT: match your Job name!
  ports:
    - name: http
      port: 8000                # container port
      targetPort: 8000
      nodePort: 30125           # external port you want